package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ApplicantfeedbackId generated by hbm2java
 */
@Entity
@Embeddable
@Table(name = "ApplicantfeedbackId", uniqueConstraints = {
		@UniqueConstraint(columnNames = {"jobid", "candidateid"}),
		})
public class ApplicantfeedbackId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7769293456096876191L;
	private int candidateid;
	@Id
	@GeneratedValue(generator = "feedbackid")
	@GenericGenerator(name = "feedbackid", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "sequence_name", value = "feedbackid"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
	private int feedbackid;
	private int jobid;
	private String stampuser;
	private int statusid;
	private String comments;
	private Date stampdate;
	private String userid;

	public ApplicantfeedbackId() {
	}

	public ApplicantfeedbackId(int feedbackid, int candidateid, int jobid, String stampuser,
			int statusid, String userid) {
		this.feedbackid = feedbackid;
		this.candidateid = candidateid;
		this.jobid = jobid;
		this.stampuser = stampuser;
		this.statusid = statusid;
		this.userid = userid;
	}

	public ApplicantfeedbackId(int feedbackid, int candidateid, int jobid, String stampuser,
			int statusid, String comments, Date stampdate, String userid) {
		this.feedbackid = feedbackid;
		this.candidateid = candidateid;
		this.jobid = jobid;
		this.stampuser = stampuser;
		this.statusid = statusid;
		this.comments = comments;
		this.stampdate = stampdate;
		this.userid = userid;
	}

	@Column(name = "candidateid", nullable = false)
	public int getCandidateid() {
		return this.candidateid;
	}

	public void setCandidateid(int candidateid) {
		this.candidateid = candidateid;
	}

	@Column(name = "jobid", nullable = false)
	public int getJobid() {
		return this.jobid;
	}

	public void setJobid(int jobid) {
		this.jobid = jobid;
	}

	@Column(name = "stampuser", nullable = false, length = 50)
	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	@Column(name = "statusid", nullable = false)
	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	@Column(name = "comments" , length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "stampdate", length = 50)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	@Column(name = "userid", nullable = false)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
	
	@Id
	@GenericGenerator(name = "id", strategy = "increment")
	@GeneratedValue(generator = "id")
	@Column(name = "feedbackid", unique = true, nullable = false)
	public int getFeedbackid() {
		return feedbackid;
	}

	public void setFeedbackid(int feedbackid) {
		this.feedbackid = feedbackid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplicantfeedbackId))
			return false;
		ApplicantfeedbackId castOther = (ApplicantfeedbackId) other;

		return ((this.getFeedbackid() == castOther.getFeedbackid()) && this.getCandidateid() == castOther.getCandidateid())
				&& (this.getJobid() == castOther.getJobid())
				&& ((this.getStampuser() == castOther.getStampuser()) || (this
						.getStampuser() != null
						&& castOther.getStampuser() != null && this
						.getStampuser().equals(castOther.getStampuser())))
				&& (this.getStatusid() == castOther.getStatusid())
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getStampdate() == castOther.getStampdate()) || (this
						.getStampdate() != null
						&& castOther.getStampdate() != null && this
						.getStampdate().equals(castOther.getStampdate())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null && castOther.getUserid() != null && this
						.getUserid().equals(castOther.getUserid())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getFeedbackid();
		result = 37 * result + this.getCandidateid();
		result = 37 * result + this.getJobid();
		result = 37 * result
				+ (getStampuser() == null ? 0 : this.getStampuser().hashCode());
		result = 37 * result + this.getStatusid();
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result
				+ (getStampdate() == null ? 0 : this.getStampdate().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		return result;
	}

}
