package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment")
public class Attachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2068498913075258919L;
	private int attachmentid;
	private Candidateprofile candidateprofile;
	private Jobdetails jobdetails;
	private String attachmentpath;
	private String attachmentdescription;
	private String attachmentdata;
	private Date stampdate;

	public Attachment() {
	}

	public Attachment(int attachmentid, Candidateprofile candidateprofile,
			Jobdetails jobdetails) {
		this.attachmentid = attachmentid;
		this.candidateprofile = candidateprofile;
		this.jobdetails = jobdetails;
	}

	public Attachment(int attachmentid, Candidateprofile candidateprofile,
			Jobdetails jobdetails, String attachmentpath,
			String attachmentdescription, String attachmentdata, Date stampdate) {
		this.attachmentid = attachmentid;
		this.candidateprofile = candidateprofile;
		this.jobdetails = jobdetails;
		this.attachmentpath = attachmentpath;
		this.attachmentdescription = attachmentdescription;
		this.attachmentdata = attachmentdata;
		this.stampdate = stampdate;
	}


	@Id
	@GenericGenerator(name="id" , strategy="increment")
	@GeneratedValue(generator="id")
	@Column(name = "attachmentid", unique = true, nullable = false)
	public int getAttachmentid() {
		return this.attachmentid;
	}

	public void setAttachmentid(int attachmentid) {
		this.attachmentid = attachmentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidateid", nullable = false)
	public Candidateprofile getCandidateprofile() {
		return this.candidateprofile;
	}

	public void setCandidateprofile(Candidateprofile candidateprofile) {
		this.candidateprofile = candidateprofile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobid", nullable = false)
	public Jobdetails getJobdetails() {
		return this.jobdetails;
	}

	public void setJobdetails(Jobdetails jobdetails) {
		this.jobdetails = jobdetails;
	}

	@Column(name = "attachmentpath")
	public String getAttachmentpath() {
		return this.attachmentpath;
	}

	public void setAttachmentpath(String attachmentpath) {
		this.attachmentpath = attachmentpath;
	}

	@Column(name = "attachmentdescription")
	public String getAttachmentdescription() {
		return this.attachmentdescription;
	}

	public void setAttachmentdescription(String attachmentdescription) {
		this.attachmentdescription = attachmentdescription;
	}

	@Column(name = "attachmentdata")
	public String getAttachmentdata() {
		return this.attachmentdata;
	}

	public void setAttachmentdata(String attachmentdata) {
		this.attachmentdata = attachmentdata;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", length = 29)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

}
