package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;



/**
 * Candidateprofile generated by hbm2java
 */
@Entity
@Table(name = "candidateprofile")
public class Candidateprofile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5035802989663241610L;
	private int candidateid;
	private String candidatename;
	private Date dob;
	private long phonenumber;
	private String address;
	private long zipcode;
	private String email;
	private String candidateskillsets;
	private String candidateexperiencedetail;
	private int expInYears;
	private Boolean isfake;
	private Date stampdate;
	private Set<Jobdetails> jobs = new HashSet<Jobdetails>(0);
	
	private Set<Attachment> attachments = new HashSet<Attachment>(0);

	public Candidateprofile() {
	}

	public Candidateprofile(int candidateid, String candidatename,
			long phonenumber, long zipcode, String email,
			String candidateskillsets, String candidateexperiencedetail,
			int expInYears) {
		this.candidateid = candidateid;
		this.candidatename = candidatename;
		this.phonenumber = phonenumber;
		this.zipcode = zipcode;
		this.email = email;
		this.candidateskillsets = candidateskillsets;
		this.candidateexperiencedetail = candidateexperiencedetail;
		this.expInYears = expInYears;
	}

	public Candidateprofile(int candidateid, String candidatename, Date dob,
			long phonenumber, String address, long zipcode,
			String email, String candidateskillsets,
			String candidateexperiencedetail, int expInYears, Boolean isfake,
			Date stampdate, Set<Jobdetails> jobs,
			
			Set<Attachment> attachments) {
		this.candidateid = candidateid;
		this.candidatename = candidatename;
		this.dob = dob;
		this.phonenumber = phonenumber;
		this.address = address;
		this.zipcode = zipcode;
		this.email = email;
		this.candidateskillsets = candidateskillsets;
		this.candidateexperiencedetail = candidateexperiencedetail;
		this.expInYears = expInYears;
		this.isfake = isfake;
		this.stampdate = stampdate;
		this.setJobs(jobs);
		
		this.attachments = attachments;
	}

	
	@Id
	@GenericGenerator(name="id" , strategy="increment")
	@GeneratedValue(generator="id")
	@Column(name = "candidateid", unique = true, nullable = false)
	public int getCandidateid() {
		return this.candidateid;
	}

	public void setCandidateid(int candidateid) {
		this.candidateid = candidateid;
	}

	@Column(name = "candidatename", nullable = false, length = 100)
	public String getCandidatename() {
		return this.candidatename;
	}

	public void setCandidatename(String candidatename) {
		this.candidatename = candidatename;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 50)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "phonenumber", nullable = false)
	public long getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(long phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "address", length = 1000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "zipcode", nullable = false)
	public long getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(long zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "candidateskillsets", nullable = false, length = 100)
	public String getCandidateskillsets() {
		return this.candidateskillsets;
	}

	public void setCandidateskillsets(String candidateskillsets) {
		this.candidateskillsets = candidateskillsets;
	}

	@Column(name = "candidateexperiencedetail", nullable = false, length = 2000)
	public String getCandidateexperiencedetail() {
		return this.candidateexperiencedetail;
	}

	public void setCandidateexperiencedetail(String candidateexperiencedetail) {
		this.candidateexperiencedetail = candidateexperiencedetail;
	}

	@Column(name = "exp_in_years", nullable = false)
	public int getExpInYears() {
		return this.expInYears;
	}

	public void setExpInYears(int expInYears) {
		this.expInYears = expInYears;
	}

	@Column(name = "isfake")
	public Boolean getIsfake() {
		return this.isfake;
	}

	public void setIsfake(Boolean isfake) {
		this.isfake = isfake;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", length = 50)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateprofile")
	public Set<Attachment> getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Set<Attachment> attachments) {
		this.attachments = attachments;
	}
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "candidates")
	public Set<Jobdetails> getJobs() {
		return jobs;
	}

	public void setJobs(Set<Jobdetails> jobs) {
		this.jobs = jobs;
	}

}
