package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Validrole generated by hbm2java
 */
@Entity
@Table(name = "validrole")
public class Validrole implements java.io.Serializable {

	private int roleid;
	private String roletype;
	private String roledescription;
	private String stampuser;
	private Date stampdate;
	private int rolegroupid;

	public Validrole() {
	}

	public Validrole(int roleid, String roletype, String roledescription,
			String stampuser, Date stampdate) {
		this.roleid = roleid;
		this.roletype = roletype;
		this.roledescription = roledescription;
		this.stampuser = stampuser;
		this.stampdate = stampdate;
	}

	
	@Id
	@GenericGenerator(name="id" , strategy="increment")
	@GeneratedValue(generator="id")
	@Column(name = "roleid", unique = true, nullable = false)
	public int getRoleid() {
		return this.roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}

	@Column(name = "roletype", nullable = false, length = 100)
	public String getRoletype() {
		return this.roletype;
	}

	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}

	@Column(name = "roledescription", nullable = false, length = 500)
	public String getRoledescription() {
		return this.roledescription;
	}

	public void setRoledescription(String roledescription) {
		this.roledescription = roledescription;
	}

	@Column(name = "stampuser", nullable = false, length = 100)
	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", nullable = false, length = 100)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	@Column(name = "rolegroupid")
	public int getRolegroupid() {
		return rolegroupid;
	}

	public void setRolegroupid(int rolegroupid) {
		this.rolegroupid = rolegroupid;
	}

}
