package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Validrole generated by hbm2java
 */
@Entity
@Table(name = "validrolegroup")
public class ValidRoleGroup implements java.io.Serializable {

	private int groupid;
	private String grouptype;
	private String groupdescription;
	private String stampuser;
	private Date stampdate;

	public ValidRoleGroup() {
	}

	public ValidRoleGroup(int groupid, String grouptype, String groupdescription, String stampuser, Date stampdate) {
		this.groupid = groupid;
		this.grouptype = grouptype;
		this.groupdescription = groupdescription;
		this.stampuser = stampuser;
		this.stampdate = stampdate;
	}

	@Id
	@GenericGenerator(name = "id", strategy = "increment")
	@GeneratedValue(generator = "id")
	@Column(name = "groupid", unique = true, nullable = false)
	public int getGroupid() {
		return groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

	@Column(name = "groupdescription", nullable = false, length = 500)
	public String getGroupdescription() {
		return groupdescription;
	}

	public void setGroupdescription(String groupdescription) {
		this.groupdescription = groupdescription;
	}

	@Column(name = "stampuser", nullable = false, length = 100)
	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", nullable = false, length = 100)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	@Column(name = "grouptype", nullable = false, length = 100)
	public String getGrouptype() {
		return grouptype;
	}

	public void setGrouptype(String grouptype) {
		this.grouptype = grouptype;
	}
}
