package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Applicantfeedback generated by hbm2java
 */
@Entity
@Table(name = "applicantfeedback")
public class Applicantfeedback implements java.io.Serializable {

	private ApplicantfeedbackId id;
	private Candidateprofile candidateprofile;
	private Jobdetails jobdetails;
	private UserProfile userProfile;

	public Applicantfeedback() {
	}

	public Applicantfeedback(ApplicantfeedbackId id,
			Candidateprofile candidateprofile, Jobdetails jobdetails,
			UserProfile userProfile) {
		this.id = id;
		this.candidateprofile = candidateprofile;
		this.jobdetails = jobdetails;
		this.userProfile = userProfile;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "candidateid", column = @Column(name = "candidateid", nullable = false)),
			@AttributeOverride(name = "jobid", column = @Column(name = "jobid", nullable = false)),
			@AttributeOverride(name = "stampuser", column = @Column(name = "stampuser", nullable = false, length = 15)),
			@AttributeOverride(name = "statusid", column = @Column(name = "statusid", nullable = false)),
			@AttributeOverride(name = "comments", column = @Column(name = "comments")),
			@AttributeOverride(name = "stampdate", column = @Column(name = "stampdate", length = 29)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)) })
	public ApplicantfeedbackId getId() {
		return this.id;
	}

	public void setId(ApplicantfeedbackId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidateid", nullable = false, insertable = false, updatable = false)
	public Candidateprofile getCandidateprofile() {
		return this.candidateprofile;
	}

	public void setCandidateprofile(Candidateprofile candidateprofile) {
		this.candidateprofile = candidateprofile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobid", nullable = false, insertable = false, updatable = false)
	public Jobdetails getJobdetails() {
		return this.jobdetails;
	}

	public void setJobdetails(Jobdetails jobdetails) {
		this.jobdetails = jobdetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
	public UserProfile getUserprofile() {
		return this.userProfile;
	}

	public void setUserprofile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

}
