package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicantfeedbackId generated by hbm2java
 */
@Embeddable
public class ApplicantfeedbackId implements java.io.Serializable {

	private int candidateid;
	private int jobid;
	private String stampuser;
	private int statusid;
	private String comments;
	private Date stampdate;
	private String userid;

	public ApplicantfeedbackId() {
	}

	public ApplicantfeedbackId(int candidateid, int jobid, String stampuser,
			int statusid, String userid) {
		this.candidateid = candidateid;
		this.jobid = jobid;
		this.stampuser = stampuser;
		this.statusid = statusid;
		this.userid = userid;
	}

	public ApplicantfeedbackId(int candidateid, int jobid, String stampuser,
			int statusid, String comments, Date stampdate, String userid) {
		this.candidateid = candidateid;
		this.jobid = jobid;
		this.stampuser = stampuser;
		this.statusid = statusid;
		this.comments = comments;
		this.stampdate = stampdate;
		this.userid = userid;
	}

	@Column(name = "candidateid", nullable = false)
	public int getCandidateid() {
		return this.candidateid;
	}

	public void setCandidateid(int candidateid) {
		this.candidateid = candidateid;
	}

	@Column(name = "jobid", nullable = false)
	public int getJobid() {
		return this.jobid;
	}

	public void setJobid(int jobid) {
		this.jobid = jobid;
	}

	@Column(name = "stampuser", nullable = false, length = 15)
	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	@Column(name = "statusid", nullable = false)
	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "stampdate", length = 29)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

	@Column(name = "userid", nullable = false)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplicantfeedbackId))
			return false;
		ApplicantfeedbackId castOther = (ApplicantfeedbackId) other;

		return (this.getCandidateid() == castOther.getCandidateid())
				&& (this.getJobid() == castOther.getJobid())
				&& ((this.getStampuser() == castOther.getStampuser()) || (this
						.getStampuser() != null
						&& castOther.getStampuser() != null && this
						.getStampuser().equals(castOther.getStampuser())))
				&& (this.getStatusid() == castOther.getStatusid())
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getStampdate() == castOther.getStampdate()) || (this
						.getStampdate() != null
						&& castOther.getStampdate() != null && this
						.getStampdate().equals(castOther.getStampdate())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null && castOther.getUserid() != null && this
						.getUserid().equals(castOther.getUserid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCandidateid();
		result = 37 * result + this.getJobid();
		result = 37 * result
				+ (getStampuser() == null ? 0 : this.getStampuser().hashCode());
		result = 37 * result + this.getStatusid();
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result
				+ (getStampdate() == null ? 0 : this.getStampdate().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		return result;
	}

}
