package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobcandidatemap generated by hbm2java
 */
@Entity
@Table(name = "jobcandidatemap")
public class Jobcandidatemap implements java.io.Serializable {

	private int mappingkey;
	private Candidateprofile candidateprofile;
	private Jobdetails jobdetails;
	private Date stampdate;

	public Jobcandidatemap() {
	}

	public Jobcandidatemap(int mappingkey, Candidateprofile candidateprofile,
			Jobdetails jobdetails) {
		this.mappingkey = mappingkey;
		this.candidateprofile = candidateprofile;
		this.jobdetails = jobdetails;
	}

	public Jobcandidatemap(int mappingkey, Candidateprofile candidateprofile,
			Jobdetails jobdetails, Date stampdate) {
		this.mappingkey = mappingkey;
		this.candidateprofile = candidateprofile;
		this.jobdetails = jobdetails;
		this.stampdate = stampdate;
	}

	@Id
	@Column(name = "mappingkey", unique = true, nullable = false)
	public int getMappingkey() {
		return this.mappingkey;
	}

	public void setMappingkey(int mappingkey) {
		this.mappingkey = mappingkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidateid", nullable = false)
	public Candidateprofile getCandidateprofile() {
		return this.candidateprofile;
	}

	public void setCandidateprofile(Candidateprofile candidateprofile) {
		this.candidateprofile = candidateprofile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobid", nullable = false)
	public Jobdetails getJobdetails() {
		return this.jobdetails;
	}

	public void setJobdetails(Jobdetails jobdetails) {
		this.jobdetails = jobdetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", length = 29)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

}
