package com.rqms.domain;

// default package
// Generated May 28, 2014 12:44:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Validstatus generated by hbm2java
 */
@Entity
@Table(name = "validstatus")
public class Validstatus implements java.io.Serializable {

	private int statusid;
	private String statustype;
	private String statusdescription;
	private String stampuser;
	private Date stampdate;

	public Validstatus() {
	}

	public Validstatus(int statusid, String statustype,
			String statusdescription, String stampuser, Date stampdate) {
		this.statusid = statusid;
		this.statustype = statustype;
		this.statusdescription = statusdescription;
		this.stampuser = stampuser;
		this.stampdate = stampdate;
	}

	@Id
	@Column(name = "statusid", unique = true, nullable = false)
	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	@Column(name = "statustype", nullable = false, length = 20)
	public String getStatustype() {
		return this.statustype;
	}

	public void setStatustype(String statustype) {
		this.statustype = statustype;
	}

	@Column(name = "statusdescription", nullable = false, length = 50)
	public String getStatusdescription() {
		return this.statusdescription;
	}

	public void setStatusdescription(String statusdescription) {
		this.statusdescription = statusdescription;
	}

	@Column(name = "stampuser", nullable = false, length = 15)
	public String getStampuser() {
		return this.stampuser;
	}

	public void setStampuser(String stampuser) {
		this.stampuser = stampuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stampdate", nullable = false, length = 29)
	public Date getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(Date stampdate) {
		this.stampdate = stampdate;
	}

}
